general {
    lock_cmd = none
    before_sleep_cmd = none
    after_sleep_cmd = none
    ignore_dbus_inhibit = false
}

listener {
    timeout = 1800
    on-timeout = brightnessctl set 20%
    on-resume = brightnessctl set 100%
}
